[package]
name = "chip8_emulator"
version = "0.1.0"
authors = ["Liron-Berger <lironberger13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.31.0"
gl = "0.14.0"

